services:
  web-tv-remote-control:
    container_name: web-tv-remote-control
    ## needed for controller mode
    # network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ## devices are only needed if you are running both or api mode
    devices:
      - /dev/uinput:/dev/uinput
    ports:
      - '8080:8080'
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - PUID=1000
      - PGID=1000
      ## remove these sections depending on (api|controller)
      ## api mode
      # - MODE=api
      # - API_TOKEN=secret # generated into the docker log on run once in api mode
      ## controller mode
      # - MODE=controller
      # - API_TOKEN=secret # get this from api container
      # - API_URL=https://api.domain.tld
      # - API_MACADDRESS=xx:xx:xx:xx:xx:xx
      # - SSH_USER=user
      # - SSH_HOST=api.domain.tld
      # - SSH_PORT=22
    volumes:
      ## needed for controller mode
      # - ./config:/config:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
