services:
  web-tv-remote-control:
    container_name: web-tv-remote-control
    build:
      context: .
      dockerfile: Dockerfile
    # devices are only needed if you are running normal or api mode
    devices:
      - /dev/uinput:/dev/uinput
    ports:
      - '8080:8080'
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - PUID=1000
      - PGID=1000
      # only fill these values in if you are using the controller/api
      # you can run with api mode once to generate you a random api key to copy from logs
      # - MODE={controller,api}
      # - API_TOKEN=secret
      # - API_URL=https://my-api.domain.tld
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
